sudo: required
services:
  - docker

before_install:
  - docker build -t bcamba/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bcamba/docker-react yarn test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-583248396190"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
